name: traj2action
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - python=3.10.16
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - albumentations==0.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - anykeystore==0.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asn1crypto==1.5.1
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==25.3.0
      - av==14.3.0
      - azure-core==1.34.0
      - azure-identity==1.23.0
      - azure-storage-blob==12.25.1
      - azure-storage-file-datalake==12.20.0
      - babel==2.17.0
      - bcrypt==4.3.0
      - bddl==3.5.0
      - beautifulsoup4==4.13.4
      - better-exceptions==0.3.3
      - bidict==0.23.1
      - bitsandbytes==0.41.0
      - bleach==6.2.0
      - blessed==1.20.0
      - boto3==1.40.0
      - botocore==1.40.0
      - braceexpand==0.1.7
      - brotli==1.1.0
      - cachetools==5.3.3
      - catalogue==2.0.10
      - certifi==2024.2.2
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - circuitbreaker==2.1.3
      - click==8.1.7
      - clip==0.2.0
      - clip-openai==1.0.post20230121
      - cloudpickle==3.1.1
      - cmake==4.0.2
      - comm==0.2.2
      - contourpy==1.3.2
      - cramjam==2.8.3
      - crcmod==1.7
      - cryptacular==1.6.2
      - cryptography==39.0.2
      - cycler==0.12.1
      - datasets==3.3.2
      - debugpy==1.8.14
      - decorator==5.1.1
      - deepspeed==0.14.2
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - diffusers==0.32.2
      - dill==0.3.8
      - distlib==0.3.8
      - distro-info==1.0
      - dm-tree==0.1.9
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - draccus==0.11.5
      - easydict==1.13
      - ecdsa==0.19.0
      - einops==0.6.0
      - einops-exts==0.0.4
      - evdev==1.9.2
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fairscale==0.4.13
      - fastapi==0.115.12
      - fastjsonschema==2.21.1
      - fastparquet==2024.5.0
      - ffmpegcv==0.3.13
      - filelock==3.14.0
      - fire==0.6.0
      - flash-attn==2.7.3
      - flatbuffers==25.2.10
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - ftfy==6.2.0
      - future==1.0.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.25.0rc1
      - google-auth==2.40.1
      - google-cloud-core==2.4.3
      - google-cloud-storage==2.10.0
      - google-crc32c==1.7.1
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - gpustat==1.1.1
      - gradio-client==0.2.9
      - greenlet==3.0.3
      - grpcio==1.64.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gym-pusht==0.1.5
      - gymnasium==1.1.1
      - h11==0.16.0
      - h5py==3.13.0
      - hf-transfer==0.1.9
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.31.2
      - hupper==1.12.1
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - idna==3.7
      - imageio==2.34.1
      - imageio-ffmpeg==0.6.0
      - imgaug==0.2.6
      - importlib-metadata==8.7.0
      - iniconfig==2.0.0
      - ipaddress==1.0.23
      - ipdb==0.13.13
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - isodate==0.7.2
      - isoduration==20.11.0
      - jaxtyping==0.2.28
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.12.0
      - jsonargparse==4.14.1
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - jupytext==1.17.1
      - keras==3.9.2
      - kiwisolver==1.4.5
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - latex2mathml==3.78.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning==2.2.3
      - lightning-utilities==0.11.2
      - lit==18.1.6
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markdown2==2.5.3
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - miscreant==0.3.0
      - mistune==3.1.3
      - ml-dtypes==0.5.1
      - mosaicml-streaming==0.12.0
      - mpmath==1.3.0
      - msal==1.32.3
      - msal-extensions==1.3.1
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - namex==0.0.9
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - nltk==3.9.1
      - notebook==7.4.2
      - notebook-shim==0.2.4
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - oci==2.152.0
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - openai-clip==1.0.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==3.4.18.65
      - openpi-client==0.1.0
      - opt-einsum==3.4.0
      - optree==0.15.0
      - overrides==7.7.0
      - packaging==22.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - paramiko==3.5.1
      - parquet==1.3.1
      - parso==0.8.4
      - pastedeploy==3.1.0
      - pathlib2==2.3.7.post1
      - pathtools==0.1.2
      - pbkdf2==1.3
      - peft==0.15.2
      - pexpect==4.9.0
      - pillow==10.3.0
      - pip==25.1.1
      - plaster==1.1.2
      - plaster-pastedeploy==1.0.1
      - platformdirs==4.2.2
      - plotly==5.22.0
      - pluggy==1.5.0
      - ply==3.11
      - prettytable==3.16.0
      - prometheus-client==0.22.0
      - promise==2.3
      - prompt-toolkit==3.0.43
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - py-spy==0.3.14
      - pyarrow==20.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodomex==3.20.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyecharts==2.0.8
      - pygame==2.6.1
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pymunk==6.11.1
      - pynacl==1.5.0
      - pynput==1.8.1
      - pynvml==11.5.0
      - pyope==0.2.2
      - pyopenssl==23.2.0
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - pyramid==2.0.2
      - pyramid-mailer==0.15.1
      - pytest==6.2.5
      - python-consul==1.1.0
      - python-dateutil==2.9.0.post0
      - python-engineio==4.9.1
      - python-etcd==0.4.5
      - python-jose==3.3.0
      - python-json-logger==3.3.0
      - python-snappy==0.7.3
      - python-socketio==5.11.2
      - python-xlib==0.33
      - python3-openid==3.2.0
      - pytorch-extension==0.2
      - pytorch-lightning==2.2.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyyaml-include==1.4.1
      - pyzmq==26.4.0
      - referencing==0.36.2
      - regex==2024.5.15
      - repoze-sendmail==4.4.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - robosuite==1.4.1
      - rpds-py==0.25.0
      - rsa==4.9
      - s3transfer==0.13.0
      - safetensors==0.4.3
      - schedule==1.2.2
      - scikit-image==0.22.0
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - setuptools==80.7.1
      - shapely==2.1.0
      - shortuuid==1.0.13
      - shtab==1.7.2
      - simple-websocket==1.0.0
      - simplejson==3.20.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==2.0.30
      - stack-data==0.6.3
      - starlette==0.46.2
      - submitit==1.5.2
      - svgwrite==1.4.3
      - swankit==0.2.4
      - swanlab==0.6.5
      - sympy==1.12
      - taming-transformers-rom1504==0.0.6
      - tenacity==8.3.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - thriftpy2==0.5.0
      - tifffile==2024.5.22
      - timm==1.0.3
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.2.1
      - torch-fidelity==0.3.0
      - torchmetrics==1.4.0.post0
      - torchvision==0.17.1
      - tornado==6.5
      - tox==3.28.0
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transaction==4.0
      - transformers==4.51.0
      - translationstring==1.4
      - tree==0.2.4
      - triton==2.2.0
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.14.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tyro==0.9.20
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==1.26.18
      - uvicorn==0.34.2
      - velruse==1.1.1
      - venusian==3.1.0
      - virtualenv==20.26.2
      - wandb==0.19.11
      - watchdog==4.0.1
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webdataset==0.2.86
      - webencodings==0.5.1
      - webob==1.8.7
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - wsproto==1.2.0
      - wtforms==3.1.2
      - wtforms-recaptcha==0.3.2
      - xformers==0.0.25
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.21.0
      - zope-deprecation==5.0
      - zope-interface==6.4.post2
      - zope-sqlalchemy==3.1
      - zstd==1.5.7.0

